name: flutter_command_pattern
description: A powerful and elegant command pattern implementation for Flutter with pipeline support, observers, and state management.
version: 1.0.1
homepage: https://github.com/cesar-marino/flutter_command_pattern
repository: https://github.com/cesar-marino/flutter_command_pattern
issue_tracker: https://github.com/cesar-marino/flutter_command_pattern/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - command-pattern
  - state-management
  - architecture
  - pipeline